
system "clear"

def new_page(second = 5)
  second.times do |i|
    sleep 1
    print '.'
  end
  system "clear"
end

new_page

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 1 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 2 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 3 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 4 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 5 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 6 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 7 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 8 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 9 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print "10 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|----------------------------------------\r\n"

new_page 3

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "                                            \r\n"
print " 1                                          \r\n"
print "                                            \r\n"
print " 2               |                          \r\n"
print "                                            \r\n"
print " 3       -   -   |   -   -                  \r\n"
print "                                            \r\n"
print " 4               |                          \r\n"
print "                                            \r\n"
print " 5           -   |   -                      \r\n"
print "                                            \r\n"
print " 6                                          \r\n"
print "                                            \r\n"
print " 7                                          \r\n"
print "                                            \r\n"
print " 8                                          \r\n"
print "                                            \r\n"
print " 9                                          \r\n"
print "                                            \r\n"
print "10                                          \r\n"
print "                                            \r\n"

new_page 3

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "                                            \r\n" 
print " 1                                          \r\n"
print "                                            \r\n"
print " 2              |||                         \r\n"
print "                                            \r\n"
print " 3       =   =  |||  =   =                  \r\n"
print "                                            \r\n"
print " 4              |||                         \r\n"
print "                                            \r\n"
print " 5           =  |||  =                      \r\n"
print "                                            \r\n"
print " 6                                          \r\n"
print "                                            \r\n"
print " 7                                          \r\n"
print "                                            \r\n"
print " 8                                          \r\n"
print "                                            \r\n"
print " 9                                          \r\n"
print "                                            \r\n"
print "10                                          \r\n"
print "                                            \r\n"

new_page 3

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     =   =  |||  =   =                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   =  |||  =   =                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   X  |||  =   =                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   X   X   =   =                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   X   X   X   =                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   X   X   X   X                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     X   X   X   X   X                 \r\n"
print "   |                                       \r\n"
print " 4 |             X                         \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"


new_page 1

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |             X                         \r\n"
print "   |                                       \r\n"
print " 3 |     X   X   X   X   X                 \r\n"
print "   |                                       \r\n"
print " 4 |             X                         \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page 1

puts "炸飞机"
puts "开始游戏"

get



