
system "clear"

def new_page(second = 1)
  second.times do |i|
    sleep 1
    print '.'
  end
  system "clear"
  
  puts "                    炸飞机                   "
end

new_page 5
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     =   =  |||  =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     =   =  |||  =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     =   =  |||  =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   =  |||  =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   X  |||  =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   X   X   =   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   X   X   X   =                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   X   X   X   X                  "
puts "   |                                        "
puts " 4 |            |||                         "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |            |||                         "
puts "   |                                        "
puts " 3 |     X   X   X   X   X                  "
puts "   |                                        "
puts " 4 |             X                          "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |             X                          "
puts "   |                                        "
puts " 3 |     X   X   X   X   X                  "
puts "   |                                        "
puts " 4 |             X                          "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "   | A   B   C   E   F   G   H   I   J   K  "
puts "---|----------------------------------------" 
puts " 1 |                                        "
puts "   |                                        "
puts " 2 |             X                          "
puts "   |                                        "
puts " 3 |     X   X   X   X   X                  "
puts "   |                                        "
puts " 4 |             X                          "
puts "   |                                        "
puts " 5 |         =  |||  =                      "
puts "   |                                        "
puts " 6 |                                        "
puts "   |                                        "
puts " 7 |                                        "
puts "   |                                        "
puts " 8 |                                        "
puts "   |                                        "
puts " 9 |                                        "
puts "   |                                        "
puts "10 |                                        "
puts "   |                                        "

new_page
puts "输入回车 开始游戏"
gets



