
def new_page
  5.times do |i|
    print '.'
    sleep 1
  end
  systmen "clear"
end

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 1 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 2 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 3 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 4 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 5 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 6 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 7 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 8 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print " 9 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|---|---|---|---|---|---|---|---|---|---|\r\n"
print "10 |   |   |   |   |   |   |   |   |   |   |\r\n"
print "---|----------------------------------------\r\n"

new_page

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "                                            \r\n"
print " 1                                          \r\n"
print "                                            \r\n"
print " 2               |                          \r\n"
print "                                            \r\n"
print " 3       -   -   |   -   -                  \r\n"
print "                                            \r\n"
print " 4               |                          \r\n"
print "                                            \r\n"
print " 5           -   |   -                      \r\n"
print "                                            \r\n"
print " 6                                          \r\n"
print "                                            \r\n"
print " 7                                          \r\n"
print "                                            \r\n"
print " 8                                          \r\n"
print "                                            \r\n"
print " 9                                          \r\n"
print "                                            \r\n"
print "10                                          \r\n"
print "                                            \r\n"

new_page

print "     A   B   C   E   F   G   H   I   J   K  \r\n"
print "                                            \r\n" 
print " 1                                          \r\n"
print "                                            \r\n"
print " 2              |||                         \r\n"
print "                                            \r\n"
print " 3       =   =  |||  =   X                  \r\n"
print "                                            \r\n"
print " 4              |||                         \r\n"
print "                                            \r\n"
print " 5           =  |||  =                      \r\n"
print "                                            \r\n"
print " 6                                          \r\n"
print "                                            \r\n"
print " 7                                          \r\n"
print "                                            \r\n"
print " 8                                          \r\n"
print "                                            \r\n"
print " 9                                          \r\n"
print "                                            \r\n"
print "10                                          \r\n"
print "                                            \r\n"

new_page

print "   | A   B   C   E   F   G   H   I   J   K  \r\n"
print "---|----------------------------------------\r\n" 
print " 1 |                                       \r\n"
print "   |                                       \r\n"
print " 2 |            |||                        \r\n"
print "   |                                       \r\n"
print " 3 |     =   =  |||  =   X                 \r\n"
print "   |                                       \r\n"
print " 4 |            |||                        \r\n"
print "   |                                       \r\n"
print " 5 |         =  |||  =                     \r\n"
print "   |                                       \r\n"
print " 6 |                                       \r\n"
print "   |                                       \r\n"
print " 7 |                                       \r\n"
print "   |                                       \r\n"
print " 8 |                                       \r\n"
print "   |                                       \r\n"
print " 9 |                                       \r\n"
print "   |                                       \r\n"
print "10 |                                       \r\n"
print "   |                                       \r\n"

new_page
